allowBuilds:
  '@swc/core': true
catalog:
  vite: 'https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-core@1738'
  vite-plus: 'https://pkg.pr.new/voidzero-dev/vite-plus@1738'
  vitest: 'https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-test@1738'
onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - unrs-resolver
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'

minimumReleaseAge: 60
minimumReleaseAgeExclude:
  - vite-plus
  - vite
  - vitest
  - '@voidzero-dev/*'
  - '@oxc-project/*'
  - '@oxlint/*'
  - oxlint
  - oxfmt
  - oxlint-tsgolint
blockExoticSubdeps: false
