allowBuilds:
  '@swc/core': true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: https://pkg.pr.new/voidzero-dev/vite-plus@1588
  vitest: ^4.1.5
onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - unrs-resolver
overrides:
  vite: 'catalog:'
  '@voidzero-dev/vite-plus-core': https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-core@5577b0154f33d1480a3c96347e94fa5d2094de2e
  '@voidzero-dev/vite-plus-prompts': https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-prompts@5577b0154f33d1480a3c96347e94fa5d2094de2e
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
blockExoticSubdeps: false
minimumReleaseAge: 60
minimumReleaseAgeExclude:
  - vite-plus
  - '@voidzero-dev/*'
  - '@oxc-project/*'
  - '@oxlint/*'
  - oxlint
  - oxfmt
  - oxlint-tsgolint
  - vitest
  - '@vitest/*'
