allowBuilds:
  '@swc/core': true
catalog:
  vite: 'https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-core@1856'
  vite-plus: 'https://pkg.pr.new/voidzero-dev/vite-plus@1856'
  vitest: '4.1.9'
onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - unrs-resolver
overrides:
  vite: 'https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-core@1856'
  vitest: '4.1.9'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
minimumReleaseAge: 60
minimumReleaseAgeExclude:
  - '@voidzero-dev/*'
  - vite-plus
  - '@vitest/*'
  - vite
  - vitest
  - '@oxc-project/*'
  - '@oxlint/*'
  - oxlint
  - oxfmt
  - oxlint-tsgolint
blockExoticSubdeps: false
